Repository CarlosCerdaMorales/dp2-c1-034, pull requests merged in 2025-03, with the labels that each got.

#252 feat: :construction: Assistance agent data model
  src/main/java/acme/entities/AssistanceAgent.java
Labels: student 4, mandatory, developer, feat, individual

#251 S01 manager role
  src/main/java/acme/entities/Airport.java
  src/main/java/acme/entities/Flight.java
  src/main/java/acme/entities/FlightStatus.java
  src/main/java/acme/entities/Leg.java
  src/main/java/acme/realms/Manager.java
Labels: student 1, mandatory, developer, feat, individual

#253 feat: :boom: Claim data model done
  src/main/java/acme/entities/Claim.java
  src/main/java/acme/entities/ClaimType.java
Labels: student 4, mandatory, developer, feat, individual

#256 fix: :green_heart: Anottation corrections in few entites.
  src/main/java/acme/entities/Aircraft.java
  src/main/java/acme/entities/Airport.java
  src/main/java/acme/entities/AssistanceAgent.java
  src/main/java/acme/entities/Booking.java
  src/main/java/acme/entities/Flight.java
  src/main/java/acme/entities/Leg.java
  src/main/java/acme/entities/MaintenanceRecord.java
  src/main/java/acme/entities/Review.java
  src/main/java/acme/entities/Service.java
  src/main/java/acme/entities/Task.java
  src/main/java/acme/realms/Manager.java
  src/main/java/acme/realms/Technician.java
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: mandatory, developer, fix

#257 feat: :heavy_plus_sign: Trackinglog data model done
  src/main/java/acme/entities/TrackingLog.java
Labels: student 4, mandatory, developer, feat, individual

#285 feat: :sparkles: Added relationships for student two's entities
  src/main/java/acme/entities/airline/Airline.java
  src/main/java/acme/entities/booking/Booking.java
  src/main/java/acme/realms/Passenger.java
  src/main/java/acme/relationships/IsFrom.java
Labels: student 2, mandatory, developer

#294 fix: :bug: Fixed attributes phone into Phone type instead of String with pattern
  src/main/java/acme/realms/Customer.java
Labels: student 2, mandatory, developer

#296 feat: :sparkles: Squads introduced into project
  src/main/java/acme/realms/Client.java
  src/main/java/acme/realms/Worker.java
Labels: student 2, developer

#304 D02 s01 models relations
  reports/Student #1/Deliverable 02/D02-Link-Dashboard-Student #1.txt
  reports/Student #1/Deliverable 02/DUMMY.txt
  src/main/java/acme/entities/flight/Flight.java
  src/main/java/acme/realms/Manager.java
  src/main/java/acme/relationships/FliesFromTo.java
  src/main/java/acme/relationships/IsComposedBy.java
  src/main/java/acme/relationships/OperatedBy.java
  src/main/java/acme/relationships/OperatesAt.java
Labels: student 1, mandatory, developer, feat, individual

#306 feat: :sparkles: S4 ,service relations done and tracking log validator added
  src/main/java/acme/constraints/TrackingLogValidator.java
  src/main/java/acme/constraints/ValidTrackingLog.java
  src/main/java/acme/entities/claim/Claim.java
  src/main/java/acme/entities/service/Service.java
  src/main/java/acme/entities/trackinglog/TrackingLog.java
  src/main/java/acme/entities/trackinglog/TrackingLogStatus.java
Labels: student 4, mandatory, suplementary I, developer, feat

#305 feat: :sparkles: Assorted sample data for student 2
  src/main/java/acme/entities/booking/Booking.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/data/sample/customer.csv
  src/main/resources/WEB-INF/data/sample/flight.csv
  src/main/resources/WEB-INF/data/sample/isFrom.csv
  src/main/resources/WEB-INF/data/sample/passenger.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: student 2, mandatory, developer, feat, individual

#307 D02 s01 models relations
  src/main/java/acme/entities/flight/Flight.java
  src/main/java/acme/entities/flight/FlightRepository.java
  src/main/java/acme/entities/leg/Leg.java
  src/main/java/acme/relationships/IsComposedBy.java
Labels: student 1, mandatory, developer, feat, individual

#319 fix: :bug: fixing main status
  src/main/java/acme/entities/flight/Flight.java
  src/main/resources/WEB-INF/data/sample/activityLog.csv
  src/main/resources/WEB-INF/data/sample/flightAssignment.csv
  src/main/resources/WEB-INF/data/sample/flightCrewMember.csv
Labels: bug

#309 docs: :memo: Student #4 uml added
  reports/Student #4/Deliverable 02/D02-Individual-UML-Student #4.jpg
  reports/Student #4/Deliverable 02/D02-Individual-UML-Student #4.uxf
Labels: student 4, individual, documentation

#308 documentation: :sparkles: UML fixed relations according to the discussion board
  reports/Group/Deliverable 02/UML Domain Model/UML - All entities.jpg
  reports/Group/Deliverable 02/UML Domain Model/UML- All entities.uxf
Labels: mandatory, group, documentation

#322 feat: Deletion of Phone turned into String with ValidString
  src/main/java/acme/components/PhoneFormatter.java
  src/main/java/acme/constraints/PhoneValidator.java
  src/main/java/acme/constraints/ValidPhone.java
  src/main/java/acme/datatypes/Phone.java
  src/main/java/acme/entities/airline/Airline.java
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/java/acme/realms/Client.java
  src/main/java/acme/realms/Customer.java
  src/main/java/acme/realms/Technician.java
  src/main/java/acme/realms/Worker.java
  src/main/java/acme/realms/flightcrewmember/FlightCrewMember.java
  src/main/java/acme/relationships/IsFrom.java
Labels: student 2, mandatory, developer

#324 feat: :sparkles: Airport sample data
  src/main/resources/WEB-INF/data/sample/airport.csv
Labels: developer, feat, group

#327 S01 d02 manager sample data
  src/main/resources/WEB-INF/data/sample/manager.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: student 1, mandatory, developer, feat, individual

#328 feat: :sparkles: Service, assistance agent and tracking log validator…
  src/main/java/acme/constraints/AssistanceAgentValidator.java
  src/main/java/acme/constraints/ServiceValidator.java
  src/main/java/acme/constraints/ValidAssistanceAgent.java
  src/main/java/acme/constraints/ValidService.java
  src/main/java/acme/entities/trackinglog/TrackingLogRepository.java
Labels: student 4, developer, feat

#331 feat: :sparkles: Student 2 customerdashboard
  src/main/java/acme/forms/CustomerDashboard.java
Labels: student 2, mandatory, developer, feat, individual

#333 feat: :sparkles: manager dashboard
  src/main/java/acme/forms/ManagerDashboard.java
Labels: student 1, suplementary I, developer, feat, individual

#334 feat: :lipstick: Sample data student #4 added
  src/main/java/acme/realms/AssistanceAgent.java
  src/main/resources/WEB-INF/data/sample/assistanceAgent.csv
  src/main/resources/WEB-INF/data/sample/service.csv
  src/main/resources/WEB-INF/data/sample/user-account.csv
Labels: student 4, developer, feat, individual, group

#346 fix: :bug: Fixed passport to unique
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/resources/WEB-INF/data/sample/passenger.csv
Labels: student 2, mandatory, fix

#349 feat: :pushpin: Tracking log sample data added
  src/main/java/acme/constraints/TrackingLogValidator.java
  src/main/java/acme/entities/trackinglog/TrackingLog.java
  src/main/resources/WEB-INF/data/sample/trackingLog.csv
Labels: student 4, mandatory, developer, feat, individual

#352 feat: :construction_worker: Assistance agent dashboard added
  src/main/java/acme/forms/AssistanceAgentDashboard.java
  src/main/java/acme/forms/statistics/StatsAssistanceAgent.java
Labels: student 4, suplementary I, developer, feat

#355 feat: :sparkles: Review sample data
  src/main/resources/WEB-INF/data/sample/review.csv
Labels: mandatory, developer, feat, group

#357 S01 d02 validators
  src/main/java/acme/constraints/LegValidator.java
  src/main/java/acme/constraints/ManagerValidator.java
  src/main/java/acme/constraints/ValidLeg.java
  src/main/java/acme/constraints/ValidManager.java
  src/main/java/acme/entities/leg/Leg.java
  src/main/java/acme/realms/Manager.java
  src/main/java/acme/relationships/FliesFromTo.java
  src/main/java/acme/relationships/OperatedBy.java
  src/main/java/acme/relationships/OperatesAt.java
  src/main/resources/WEB-INF/data/sample/airport.csv
  src/main/resources/WEB-INF/data/sample/leg.csv
  src/main/resources/WEB-INF/data/sample/operatedBy.csv
  src/main/resources/WEB-INF/data/sample/operatesAt.csv
Labels: student 1, developer, individual

#353 docs: :memo: Link to individual dashboard added
  reports/Student #4/Deliverable 02/D02-Link-Dashboard-Student #4.txt
Labels: student 4, individual, documentation

#359 refactor: :recycle: numerous corrections based on requirements and co…
  src/main/java/acme/entities/aircraft/Aircraft.java
  src/main/java/acme/entities/booking/Booking.java
  src/main/java/acme/entities/claim/Claim.java
  src/main/java/acme/entities/flightassignment/FlightAssignment.java
  src/main/java/acme/entities/leg/Leg.java
  src/main/java/acme/entities/maintenancerecord/MaintenanceRecord.java
  src/main/java/acme/entities/passenger/Passenger.java
  src/main/java/acme/entities/service/Service.java
  src/main/java/acme/entities/task/Task.java
  src/main/java/acme/entities/trackinglog/TrackingLog.java
  src/main/java/acme/realms/AssistanceAgent.java
  src/main/java/acme/realms/Customer.java
  src/main/java/acme/realms/Manager.java
  src/main/java/acme/realms/Technician.java
  src/main/java/acme/realms/flightcrewmember/FlightCrewMember.java
  src/main/resources/WEB-INF/data/sample/aircraft.csv
  src/main/resources/WEB-INF/data/sample/service.csv
Labels: developer, group, bug

#362 docs: :memo: UMLs all entities updated and misc created
  reports/Group/Deliverable 02/UML Domain Model/UML - All entities.jpg
  reports/Group/Deliverable 02/UML Domain Model/UML - All entities.uxf
  reports/Group/Deliverable 02/UML Domain Model/UML - Miscellaneous.jpg
  reports/Group/Deliverable 02/UML Domain Model/UML - Miscellaneous.uxf
Labels: mandatory, developer, documentation

#363 feat: :sparkles: customer dashboard
  src/main/java/acme/forms/CustomerDashboard.java
  src/main/java/acme/forms/ManagerDashboard.java
  src/main/java/acme/forms/statistics/StatsCustomer.java
  src/main/java/acme/forms/statistics/StatsManager.java
Labels: student 1, student 2, suplementary I, developer, individual

#372 docs: :money_with_wings: Student 4 requirements doc
  reports/Student #4/Deliverable 02/D02-Requirements-Student #4.docx
Labels: student 4, mandatory, individual, documentation

#371 docs: :money_with_wings: UMLs fixed according to the changes made on …
  reports/Group/Deliverable 02/UML Domain Model/UML - All entities.uxf
  reports/Group/Deliverable 02/UML Domain Model/UML - Miscellaneous.uxf
Labels: mandatory, fix, group, documentation

#370 feat: :coffin: Tracking log attributes fixed and resolutionPercentage.
  src/main/java/acme/constraints/TrackingLogValidator.java
  src/main/java/acme/entities/claim/Claim.java
  src/main/java/acme/entities/trackinglog/TrackingLogRepository.java
  src/main/resources/WEB-INF/data/sample/claim.csv
  src/main/resources/WEB-INF/data/sample/trackingLog.csv
Labels: student 4, mandatory, developer, feat, individual

#375 docs: :memo: Student 2 requirements file
  reports/Student #2/Deliverable 02/D02-Requirements-Student #2.docx
Labels: student 2, mandatory, documentation

#376 docs: :clown_face: UML student #4 fixed
  reports/Student #4/Deliverable 02/D02-Individual-UML-Student #4.jpg
  reports/Student #4/Deliverable 02/D02-Individual-UML-Student #4.uxf
  reports/Student #4/Deliverable 02/D02-UML-Miscellaneous-Student#4.jpg
  reports/Student #4/Deliverable 02/D02-UML-Miscellaneous-Student#4.uxf
Labels: student 4, mandatory, individual, documentation

#378 docs: :wrench: Miscellaneous administrator dashboard fixed
  reports/Group/Deliverable 02/UML Domain Model/UML - Miscellaneous.uxf
Labels: suplementary I, group, documentation

#396 feat: :building_construction: Validations messages added
  src/main/java/acme/constraints/AssistanceAgentValidator.java
  src/main/java/acme/constraints/ServiceValidator.java
  src/main/java/acme/constraints/TrackingLogValidator.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: student 4, mandatory, developer, feat, individual, group

#402 docs: :memo: Requirements D02 group
  reports/Group/Deliverable 02/D02-Requirements-Group.docx
Labels: mandatory, developer, group, documentation

#404 docs: :busts_in_silhouette: UML miscellaneous jpg
  reports/Group/Deliverable 02/UML Domain Model/UML - Miscellaneous.jpg
Labels: suplementary I, group, documentation

#525 fix: :fire: corrections based on the last follow up
  src/main/java/acme/constraints/LegValidator.java
  src/main/java/acme/constraints/ManagerValidator.java
  src/main/java/acme/entities/leg/Leg.java
  src/main/java/acme/relationships/OperatedBy.java
  src/main/java/acme/relationships/OperatesAt.java
  src/main/resources/WEB-INF/data/sample/operatedBy.csv
  src/main/resources/WEB-INF/data/sample/operatesAt.csv
Labels: group, bug, follow-up

#526 D03 fix customer dashboard
  src/main/java/acme/features/authenticated/customer/dashboard/CustomerDashboardController.java
  src/main/java/acme/features/authenticated/customer/dashboard/CustomerDashboardRepository.java
  src/main/java/acme/features/authenticated/customer/dashboard/CustomerDashboardShowService.java
  src/main/java/acme/forms/CustomerDashboard.java
  src/main/resources/WEB-INF/views/customer/customer-dashboard/form.jsp
  src/main/resources/WEB-INF/views/customer/customer-dashboard/messages-en.i18n
  src/main/resources/WEB-INF/views/customer/customer-dashboard/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: student 2, suplementary I, developer, fix, individual

#542 Aircraft validator
  src/main/java/acme/constraints/AircraftValidator.java
  src/main/java/acme/constraints/ValidAircraft.java
  src/main/java/acme/entities/aircraft/Aircraft.java
  src/main/java/acme/entities/airport/Airport.java
  src/main/java/acme/features/entities/aircraft/AircraftRepository.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: developer, fix, bug

#543 feat: :sparkles: Airline validator correction
  src/main/java/acme/constraints/AirlineValidator.java
  src/main/java/acme/constraints/ValidAirline.java
  src/main/java/acme/features/entities/airline/AirlineRepository.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: developer, fix, group

#545 feat: :arrow_up: Service validator added
  .classpath
  src/main/java/acme/constraints/ServiceValidator.java
  src/main/java/acme/entities/service/Service.java
  src/main/java/acme/entities/service/ServiceRepository.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: student 4, feat, group

#546 fix: :bug: Fixed Technician Validator
  src/main/java/acme/constraints/TechnicianValidator.java
  src/main/java/acme/constraints/ValidTechnician.java
  src/main/resources/WEB-INF/data/sample/technician.csv
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: developer, fix, bug

#550 fix: :bug: Fixed lastnibble expression in booking
  src/main/java/acme/constraints/BookingValidator.java
  src/main/java/acme/entities/booking/Booking.java
  src/main/resources/WEB-INF/data/sample/booking.csv
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: student 2, mandatory, developer, fix, individual

#548 Technician validator
  src/main/java/acme/constraints/TechnicianValidator.java
  src/main/java/acme/features/entities/technician/TechnicianRepository.java
  src/main/resources/WEB-INF/views/validation-en.i18n
  src/main/resources/WEB-INF/views/validation-es.i18n
Labels: student 5, feat

#552 fix: :ambulance: Service and TrackingLog validators fixed
  src/main/java/acme/constraints/ServiceValidator.java
  src/main/java/acme/constraints/TrackingLogValidator.java
  src/main/java/acme/entities/trackinglog/TrackingLog.java
Labels: student 4, developer, fix

#553 S01 d03 airline funcionalidades grupales
  reports/Student #1/Deliverable 02/D02-Individual-UML-Student #1.uxf
  src/main/java/acme/features/entities/airline/AdministratorAirlineCreateService.java
  src/main/java/acme/features/entities/airline/AdministratorAirlineListService.java
  src/main/java/acme/features/entities/airline/AdministratorAirlineShowService.java
  src/main/java/acme/features/entities/airline/AdministratorAirlineUpdateService.java
  src/main/java/acme/features/entities/airline/AirlineController.java
  src/main/java/acme/features/entities/airline/AirlineRepository.java
Labels: mandatory, developer, feat, group

#554 feat: :egg: D03 R14 group added
  src/main/java/acme/entities/service/PrincipalServiceShowService.java
  src/main/java/acme/entities/service/ServiceController.java
  src/main/java/acme/entities/service/ServiceRepository.java
Labels: mandatory, developer, feat, group

#565 D03 r14
  src/main/java/acme/constraints/ServiceValidator.java
  src/main/java/acme/features/principal/service/PrincipalServiceAdvisor.java
  src/main/java/acme/features/principal/service/PrincipalServiceShowService.java
  src/main/java/acme/features/principal/service/ServiceController.java
  src/main/java/acme/features/principal/service/ServiceRepository.java
  src/main/resources/WEB-INF/views/fragments/footer.jsp
Labels: mandatory, feat, group

#571 S01 d03 individuales
  src/main/java/acme/constraints/AirlineValidator.java
  src/main/java/acme/entities/airline/Airline.java
  src/main/java/acme/entities/flight/Flight.java
  src/main/java/acme/entities/leg/Leg.java
  src/main/java/acme/features/entities/airline/AdministratorAirlineCreateService.java
  src/main/java/acme/features/entities/airline/AdministratorAirlineListService.java
  src/main/java/acme/features/entities/airline/AdministratorAirlineRepository.java
  src/main/java/acme/features/entities/airline/AdministratorAirlineShowService.java
  src/main/java/acme/features/entities/airline/AdministratorAirlineUpdateService.java
  src/main/java/acme/features/manager/flights/ManagerFlightController.java
  src/main/java/acme/features/manager/flights/ManagerFlightCreateService.java
  src/main/java/acme/features/manager/flights/ManagerFlightDeleteService.java
  src/main/java/acme/features/manager/flights/ManagerFlightListService.java
  src/main/java/acme/features/manager/flights/ManagerFlightPublishService.java
  src/main/java/acme/features/manager/flights/ManagerFlightRepository.java
  src/main/java/acme/features/manager/flights/ManagerFlightShowService.java
  src/main/java/acme/features/manager/flights/ManagerFlightUpdateService.java
  src/main/java/acme/features/manager/legs/ManagerLegController.java
  src/main/java/acme/features/manager/legs/ManagerLegDeleteService.java
  src/main/java/acme/features/manager/legs/ManagerLegRepository.java
  src/main/resources/WEB-INF/data/sample/airline.csv
  src/main/resources/WEB-INF/data/sample/flight.csv
  src/main/resources/WEB-INF/data/sample/leg.csv
  src/main/resources/WEB-INF/views/administrator/airline/form.jsp
  src/main/resources/WEB-INF/views/administrator/airline/messages-en.i18n
  src/main/resources/WEB-INF/views/administrator/airline/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
  src/main/resources/WEB-INF/views/manager/flight/form.jsp
  src/main/resources/WEB-INF/views/manager/flight/list.jsp
  src/main/resources/WEB-INF/views/manager/flight/messages-en.i18n
  src/main/resources/WEB-INF/views/manager/flight/messages-es.i18n
Labels: student 1, developer, feat, individual

#587 feat: :egg: S4-R8 done
  src/main/java/acme/entities/claim/Claim.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimCompletedListService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimController.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimCreateService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimDeleteService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimPublishService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimRepository.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimShowService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimUndergoingListService.java
  src/main/java/acme/features/assistanceAgent/claim/AssistanceAgentClaimUpdateService.java
  src/main/resources/WEB-INF/data/sample/claim.csv
  src/main/resources/WEB-INF/views/assistance-agent/claim/form.jsp
  src/main/resources/WEB-INF/views/assistance-agent/claim/list.jsp
  src/main/resources/WEB-INF/views/assistance-agent/claim/messages-en.i18n
  src/main/resources/WEB-INF/views/assistance-agent/claim/messages-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: student 4, mandatory, developer, individual
