Repository CarlosCerdaMorales/dp2-c1-034, pull requests merged in 2025-02, with the labels that each got.

#42 fix: :bug: Modify anonymus menu so its shows correctly S01 favorite link
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
  src/main/resources/WEB-INF/views/fragments/menu.jsp
Labels: student 1, mandatory

#89 Managerial requirements link to dashboard
  reports/DUMMY.txt
  reports/Student #1/Link dashboard.txt
Labels: student 1, developer, individual, documentation

#90 docs: :memo: Provide a link to your planning dashboard in GitHub
  reports/Student #2/Link dashboard.txt
Labels: student 2, mandatory, developer, individual, documentation

#92 docs: :memo: S01-Analysis report
  reports/Student #1/S01-Analysis Report.docx
Labels: student 1, suplementary II, individual, documentation

#91 feat: :fire: Link to my dahsboard added individual R2
  reports/Student #4/Link dashboard.txt
Labels: student 4, mandatory, individual

#97 docs: :memo: Produce a report on what you knew about testing a WIS before this subject
  reports/Group/Report WIS Testing.docx
Labels: suplementary I, group, documentation

#98 docs: :memo: Provide a link to your planning dashboard in GitHub
  reports/Group/Link dashboard.txt
Labels: mandatory, developer, group

#104 docs: :memo: Analysis Report - Student #2
  reports/Student #2/Analysis Report - Student #2.docx
Labels: student 2, suplementary II, developer, individual, documentation

#114 docs: :memo: Student 2 - Planning and progress report
  reports/Student #2/Planning and Progress Report - Student #2.docx
Labels: student 2, suplementary II, developer, individual, documentation

#180 feat: :sparkles: Create groupal data models
  src/main/java/acme/entities/Aircraft.java
  src/main/java/acme/entities/AircraftStatus.java
Labels: group

#182 feat: :sparkles: Airline Data Model, group requirement 5
  src/main/java/acme/entities/Airline.java
  src/main/java/acme/entities/AirlineType.java
Labels: mandatory, developer, feat, group

#183 feat: :sparkles: airport model without releations
  src/main/java/acme/entities/Airport.java
  src/main/java/acme/entities/Scopes.java
Labels: mandatory, developer, group

#181 feat: :sparkles: Create individual data models
  src/main/java/acme/entities/MaintenanceRecord.java
  src/main/java/acme/entities/MaintenanceStatus.java
  src/main/java/acme/entities/Task.java
  src/main/java/acme/entities/TaskType.java
  src/main/java/acme/entities/Technician.java
Labels: student 5, individual

#188 fix: :bug: fix DNI numbers censorship
  src/main/resources/WEB-INF/views/fragments/menu-en.i18n
  src/main/resources/WEB-INF/views/fragments/menu-es.i18n
Labels: developer, fix

#193 fix: :bug: fix according the framework data models
  src/main/java/acme/entities/Task.java
  src/main/java/acme/entities/Technician.java
Labels: developer, fix

#239 build: :building_construction: Preparing new workspace
  CHANGELOG.txt
  pom.xml
  src/main/java/acme/entities/Airline.java
  src/main/resources/WEB-INF/views/authenticated/consumer/form.jsp
  src/main/resources/WEB-INF/views/authenticated/provider/form.jsp
Labels: manager, starting

#243 chore: :memo: Organization of docs changed. Each student has a folder for each deliverable. Same applies for group.
  reports/Group/Deliverable 01/D01-Link-Dashboard-Group.txt
  reports/Group/Deliverable 01/D01-Report-Development-Configuration.docx
  reports/Group/Deliverable 01/D01-Report-WIS-Testing.docx
  reports/Group/Deliverable 01/D01-Report-WIS.docx
  reports/Group/Deliverable 01/D01-Requirements-Group.docx
  reports/Group/Deliverable 01/Documentation Template.docx
  reports/Student #1/Deliverable 01/D01-Analysis-Report-Student #1.docx
  reports/Student #1/Deliverable 01/D01-Link-Dashboard-Student #1.txt
  reports/Student #1/Deliverable 01/D01-Planning-And-Progress-Report-Student #1.docx
  reports/Student #1/Deliverable 01/D01-Requirements-Student #1.docx
  reports/Student #2/Deliverable 01/D01-Analysis-Report-Student #2.docx
  reports/Student #2/Deliverable 01/D01-Link-Dashboard-Student #2.txt
  reports/Student #2/Deliverable 01/D01-Planning-And-Progress-Report-Student #2.docx
  reports/Student #2/Deliverable 01/D01-Requirements-Student #2.docx
  reports/Student #3/Deliverable 01/D01-Analysis-Report-Student #3.docx
  reports/Student #3/Deliverable 01/D01-Link-Dashboard-Student #3.txt
  reports/Student #3/Deliverable 01/D01-Planning-And-Progress-Report-Student #3.docx
  reports/Student #3/Deliverable 01/D01-Requirements-Student #3.docx
  reports/Student #4/Deliverable 01/D01-Analysis Report-Student #4.docx
  reports/Student #4/Deliverable 01/D01-Link Dashboard-Student #4.txt
  reports/Student #4/Deliverable 01/D01-Planning and Progress Report - Student #4.docx
  reports/Student #4/Deliverable 01/D01-Requirements-Student #4.docx
  reports/Student #5/Deliverable 01/D01-Analysis-Report-Student #5.docx
  reports/Student #5/Deliverable 01/D01-Link-Dashboard-Student #5.txt
  reports/Student #5/Deliverable 01/D01-Planning-And-Progress-Report-Student #5.docx
  reports/Student #5/Deliverable 01/D01-Requirements-Student #5.docx
Labels: manager, documentation

#244 docs: :memo: Link to dashboard student 2 deliverable 2
  reports/Group/Deliverable 02/DUMMY.txt
  reports/Student #1/Deliverable 02/DUMMY.txt
  reports/Student #2/Deliverable 02/D02-Link-Dashboard-Student #2.txt
  reports/Student #3/Deliverable 02/DUMMY.txt
  reports/Student #4/Deliverable 02/DUMMY.txt
  reports/Student #5/Deliverable 02/DUMMY.txt
Labels: student 2, mandatory, developer, individual, documentation

#246 feat: :sparkles: Customer data model requirement 3 student 2
  src/main/java/acme/realms/Customer.java
Labels: student 2, mandatory, developer, feat, individual

#248 refactor: :recycle: Refactoring identifier after being wrongly named as pattern
  src/main/java/acme/realms/Customer.java
Labels: student 2, mandatory, developer, fix, individual

#249 feat: :sparkles: D02-R4 Booking data model mandatory student 2
  src/main/java/acme/entities/Booking.java
  src/main/java/acme/entities/TravelClass.java
Labels: student 2, mandatory, developer, feat, individual
